import { useState } from 'react';
import { Link } from 'react-router-dom';

function RequirementGroup({ title, rows }) {
 return <section className="recruiter-section"><h3>{title}</h3>{rows.length ? rows.map(r => <div className="recruiter-match" key={r.name}><div><strong>{r.name}</strong><small>{r.detail}</small></div><span>{r.label}</span></div>) : <p className="recruiter-muted">None among recognised requirements.</p>}</section>;
}
function EvidenceProjects({ projects }) {
 return <section className="recruiter-section"><h3>Supporting projects</h3>{!projects.length && <p>No built projects directly support the recognised requirements.</p>}{projects.slice(0,5).map(p => <article className="recruiter-evidence" key={p.id}><h4>{p.title}</h4><small>{p.portfolioPublicationStatus === 'not-yet-published' ? 'Built · Portfolio page coming soon' : p.status}</small><p className="recruiter-relevance">Demonstrates {([...new Set(p.demonstratedMatches)].slice(0,5)).join(', ')} through built project implementation.</p><details><summary>Project scope & evidence</summary><p>{p.description || 'Built implementation supported by inspected repository evidence.'}</p><small>{p.evidence.some(e => e.type === 'source-code') ? 'Repository-supported implementation' : 'Documented project implementation'}</small></details><div className="recruiter-tags">{p.matches.map(t => <span key={t}>{t}</span>)}</div><div className="recruiter-links">{p.portfolioPublicationStatus !== 'not-yet-published' && <Link to={p.path}>View project →</Link>}{p.repository && <a href={p.repository} target="_blank" rel="noreferrer">View repository<span className="recruiter-sr"> (opens a new tab)</span></a>}</div></article>)}{projects.length > 5 && <small>{projects.length - 5} additional built projects appear in the detailed requirement evidence.</small>}</section>;
}
export default function RecruiterAssessment({ result: r }) {
 const [view, setView] = useState('overview');
 return <div className="recruiter-result">
  {(r.title || r.company) && <p className="recruiter-role-name">{r.title || 'Role assessment'}{r.company && <small>{r.company}</small>}</p>}
  <small className="recruiter-session-note">Assessment generated from current portfolio evidence</small>
  <section className="recruiter-requirements-summary"><h3>Role requirements identified</h3><div className="recruiter-tags">{r.rows.map(row => <span key={row.name} title={`${row.importance} · ${row.importanceReason}`}>{row.name}</span>)}</div></section>
  <div className="recruiter-score"><strong>{r.score}<span>%</span></strong><h3>Overall Evidence Alignment</h3><p>Based on demonstrated portfolio evidence matched against recognised role requirements.</p>
   <details><summary>How alignment is calculated</summary><p>Technology requirements carry twice the base weight of broad domains and contextual requirements. Required/essential phrasing multiplies importance by 1.5; preferred/bonus phrasing by 0.5. Repeated neutral requirements receive 1.2. Ambiguous phrasing stays neutral. Built implementations score 65, with up to 15 for additional projects, 10 for direct source/configuration evidence and 5 for supporting training. Broad domains are capped at 75. Training alone scores 25, listed capabilities 15, related domains 10 and missing evidence 0. Education context contributes 20; unverified tenure and certification requirements contribute 0. The weighted average is rounded to a whole percentage. This measures evidence coverage, not hiring probability or proficiency.</p></details>
  </div>
  <div className="recruiter-coverage"><strong>Evidence coverage: {r.evidenceCoverage}</strong><small>{r.coverageNote}</small></div>
  {!!r.importantGaps.length && <div className="recruiter-important-gaps"><RequirementGroup title="Important gaps" rows={r.importantGaps} /><p>These essential requirements remain unverified or have insufficient evidence.</p></div>}
  <dl className="recruiter-metrics"><div><dt>Requirements recognised</dt><dd>{r.rows.length}</dd></div><div><dt>Strong / good</dt><dd>{r.strong.length}</dd></div><div><dt>Partial / limited</dt><dd>{r.partial.length}</dd></div><div><dt>Evidence gaps</dt><dd>{r.gaps.length}</dd></div><div><dt>Supporting projects</dt><dd>{r.projects.length}</dd></div><div><dt>Relevant credentials</dt><dd>{r.credentials.length}</dd></div></dl>
  <div className="recruiter-view-switch" role="group" aria-label="Assessment view">{['overview','detailed'].map(v => <button key={v} type="button" aria-pressed={view === v} onClick={() => setView(v)}>{v === 'overview' ? 'Overview' : 'Detailed breakdown'}</button>)}</div>
  {view === 'overview' ? <>
   <section className="recruiter-section"><h3>Why Keeno aligns</h3><p>{r.summary}</p></section>
   <section className="recruiter-section"><h3>Technology alignment</h3>{r.rows.filter(row => row.type === 'technology').map(row => <div className="recruiter-capability" key={row.name}><div><strong>{row.name}</strong><span>{row.score}% · {row.label}</span></div><div className="recruiter-bar" aria-hidden="true"><i style={{ width: `${row.score}%` }} /></div></div>)}</section>
   {!!r.categoryAlignment.length && <section className="recruiter-section recruiter-category-alignment"><h3>Category alignment</h3><p>Weighted coverage of recognised technologies within each relevant category.</p>{r.categoryAlignment.map(category => <div className="recruiter-capability" key={category.name}><div><strong>{category.name}</strong><span>{category.score}% · {category.label}</span></div><div className="recruiter-bar" aria-hidden="true"><i style={{ width: `${category.score}%` }} /></div></div>)}</section>}
   <RequirementGroup title="Strongest matches" rows={[...r.strong].sort((a,b) => b.score-a.score)} /><RequirementGroup title="Partial matches" rows={r.partial} /><RequirementGroup title="Evidence gaps" rows={r.gaps} />
   <EvidenceProjects projects={r.projects} />
  </> : <section className="recruiter-section"><h3>Requirement-by-requirement analysis</h3>{r.rows.map(row => <article className="recruiter-requirement" key={row.name}><div className="recruiter-match"><strong>{row.name}</strong><span>{row.score}% · {row.label}</span></div><p>{row.detail}</p><small className="recruiter-requirement-meta">{row.importance} · {row.importanceReason}<br />{row.evidenceStrength}</small><p className="recruiter-strongest-evidence">Strongest support: {row.projects[0]?.title || row.credentials[0]?.name || (row.type === 'education' ? 'Computer science coursework / structured training' : 'No direct supporting record')}</p>{row.projects.map(p => <details key={p.id}><summary>{p.title} · Direct implementation</summary><p>{p.description || 'Source-supported built implementation.'}</p><div className="recruiter-links">{p.portfolioPublicationStatus !== 'not-yet-published' && <Link to={p.path}>View project</Link>}{p.repository && <a href={p.repository} target="_blank" rel="noreferrer">Repository (new tab)</a>}</div><details className="recruiter-source-details"><summary>Source records</summary><ul className="recruiter-provenance">{p.evidence.map((e,i) => <li key={i}>{e.type} · {e.strength}{e.revision ? ` · revision ${e.revision}` : ''}{e.inspectedOn ? ` · inspected ${e.inspectedOn}` : ''}<br />{e.source?.startsWith('https://') ? <a href={e.source} target="_blank" rel="noreferrer">Source record (new tab)</a> : <span>{e.source}</span>}</li>)}</ul></details></details>)}{row.credentials.map(c => <p key={c.id}><Link to={c.path}>{c.name}</Link> · {c.credentialTypes.join(' / ')} · {c.status}</p>)}</article>)}</section>}
  {!!r.credentials.length && <section className="recruiter-section"><h3>Supporting credentials & training</h3>{r.credentials.slice(0,4).map(c => <article className="recruiter-evidence" key={c.id}><small>{c.credentialTypes.join(' · ')}</small><h4>{c.name}</h4><p>{c.issuer} · {c.date}<br />{c.status}</p><p className="recruiter-relevance">Supporting training for {c.matches.join(', ')}; this is separate from project implementation.</p><div className="recruiter-links"><Link to={c.path}>View credential record →</Link>{c.verification && <a href={c.verification} target="_blank" rel="noreferrer">Issuer profile (new tab)</a>}</div></article>)}{r.credentials.length > 4 && <details><summary>Show {r.credentials.length - 4} additional credential records</summary>{r.credentials.slice(4).map(c => <p key={c.id}><Link to={c.path}>{c.name}</Link> · {c.credentialTypes.join(' · ')} · {c.status}</p>)}</details>}</section>}
  {r.rows.some(row => ['education','experience'].includes(row.type)) && <section className="recruiter-section"><h3>Education & experience context</h3>{r.rows.some(row => row.type === 'education') && r.education.map(e => <p key={e}>{e}</p>)}{r.rows.some(row => row.type === 'experience') && r.experience.map(e => <p key={e}>{e}</p>)}<Link to="/cv">Review CV →</Link></section>}
  <p className="recruiter-limitations">Local, deterministic analysis recognises portfolio technologies and {r.categoryCount} shared engineering categories, plus education, tenure and certification context. Ecosystems help retrieve evidence; related technologies do not prove a specific tool. Importance is inferred from local wording and section headings; ambiguous phrasing stays neutral. Unrecognised requirements, leadership, production scale and nontechnical criteria need manual review. Only the requirements shown contribute to the percentage.</p>
 </div>;
}
