import { useState } from 'react';
import { Link } from 'react-router-dom';

function RequirementGroup({ title, rows }) {
 return <section className="recruiter-section"><h3>{title}</h3>{rows.length ? rows.map(r => <div className="recruiter-match" key={r.name}><div><strong>{r.name}</strong><small>{r.detail}</small></div><span>{r.label}</span></div>) : <p className="recruiter-muted">None among recognised requirements.</p>}</section>;
}
function EvidenceProjects({ projects }) {
 return <section className="recruiter-section"><h3>Supporting projects</h3>{!projects.length && <p>No built projects directly support the recognised requirements.</p>}{projects.slice(0,4).map(p => <article className="recruiter-evidence" key={p.id}><h4>{p.title}</h4><small>{p.portfolioPublicationStatus === 'not-yet-published' ? 'Built · Portfolio page coming soon' : p.status}</small><p>{p.description || 'Built implementation supported by inspected repository evidence.'}</p><div className="recruiter-tags">{p.matches.map(t => <span key={t}>{t}</span>)}</div><div className="recruiter-links">{p.portfolioPublicationStatus !== 'not-yet-published' && <Link to={p.path}>View project →</Link>}{p.repository && <a href={p.repository} target="_blank" rel="noreferrer">View repository<span className="recruiter-sr"> (opens a new tab)</span></a>}</div></article>)}{projects.length > 4 && <small>{projects.length - 4} additional built projects appear in the detailed requirement evidence.</small>}</section>;
}
export default function RecruiterAssessment({ result: r }) {
 const [view, setView] = useState('overview');
 return <div className="recruiter-result">
  {(r.title || r.company) && <p className="recruiter-role-name">{r.title || 'Role assessment'}{r.company && <small>{r.company}</small>}</p>}
  <div className="recruiter-score"><strong>{r.score}<span>%</span></strong><h3>Overall Evidence Alignment</h3><p>Based on demonstrated portfolio evidence matched against recognised role requirements.</p>
   <details><summary>How alignment is calculated</summary><p>Technology requirements carry twice the weight of broad domains and contextual requirements. Built implementations score 65, with up to 15 for additional projects, 10 for direct source/configuration evidence and 5 for supporting training. Broad domains are capped at 75. Training alone scores 25, listed capabilities 15, related domains 10 and missing evidence 0. Education context contributes 20; unverified tenure and certification requirements contribute 0. The weighted average is rounded to a whole percentage. This measures evidence coverage, not hiring probability or proficiency.</p></details>
  </div>
  <dl className="recruiter-metrics"><div><dt>Requirements matched</dt><dd>{r.matched} / {r.rows.length}</dd></div><div><dt>Strong / good</dt><dd>{r.strong.length}</dd></div><div><dt>Partial / limited</dt><dd>{r.partial.length}</dd></div><div><dt>Evidence gaps</dt><dd>{r.gaps.length}</dd></div></dl>
  <div className="recruiter-view-switch" role="group" aria-label="Assessment view">{['overview','detailed'].map(v => <button key={v} type="button" aria-pressed={view === v} onClick={() => setView(v)}>{v === 'overview' ? 'Overview' : 'Detailed breakdown'}</button>)}</div>
  {view === 'overview' ? <>
   <section className="recruiter-section"><h3>Why Keeno aligns</h3><p>{r.summary}</p></section>
   <section className="recruiter-section"><h3>Capability alignment</h3>{r.rows.filter(row => ['technology','domain'].includes(row.type)).map(row => <div className="recruiter-capability" key={row.name}><div><strong>{row.name}</strong><span>{row.score}% · {row.label}</span></div><div className="recruiter-bar" aria-hidden="true"><i style={{ width: `${row.score}%` }} /></div></div>)}</section>
   <RequirementGroup title="Strongest matches" rows={[...r.strong].sort((a,b) => b.score-a.score)} /><RequirementGroup title="Partial matches" rows={r.partial} /><RequirementGroup title="Evidence gaps" rows={r.gaps} />
   <EvidenceProjects projects={r.projects} />
  </> : <section className="recruiter-section"><h3>Requirement-by-requirement analysis</h3>{r.rows.map(row => <article className="recruiter-requirement" key={row.name}><div className="recruiter-match"><strong>{row.name}</strong><span>{row.score}% · {row.label}</span></div><p>{row.detail}</p><small>Requirement type: {row.type}</small>{row.projects.map(p => <details key={p.id}><summary>{p.title} · Direct implementation</summary><p>{p.description || 'Source-supported built implementation.'}</p><div className="recruiter-links">{p.portfolioPublicationStatus !== 'not-yet-published' && <Link to={p.path}>View project</Link>}{p.repository && <a href={p.repository} target="_blank" rel="noreferrer">Repository (new tab)</a>}</div><ul className="recruiter-provenance">{p.evidence.map((e,i) => <li key={i}>{e.type} · {e.strength}{e.revision ? ` · revision ${e.revision}` : ''}{e.inspectedOn ? ` · inspected ${e.inspectedOn}` : ''}<br />{e.source?.startsWith('https://') ? <a href={e.source} target="_blank" rel="noreferrer">Source record (new tab)</a> : <span>{e.source}</span>}</li>)}</ul></details>)}{row.credentials.map(c => <p key={c.id}><Link to={c.path}>{c.name}</Link> · {c.credentialTypes.join(' / ')} · {c.status}</p>)}</article>)}</section>}
  {!!r.credentials.length && <section className="recruiter-section"><h3>Supporting credentials & training</h3>{r.credentials.slice(0,4).map(c => <article className="recruiter-evidence" key={c.id}><small>{c.credentialTypes.join(' · ')}</small><h4>{c.name}</h4><p>{c.issuer} · {c.date}<br />{c.status}</p><Link to={c.path}>View credential record →</Link></article>)}{r.credentials.length > 4 && <details><summary>Show {r.credentials.length - 4} additional credential records</summary>{r.credentials.slice(4).map(c => <p key={c.id}><Link to={c.path}>{c.name}</Link> · {c.credentialTypes.join(' · ')} · {c.status}</p>)}</details>}</section>}
  {r.rows.some(row => ['education','experience'].includes(row.type)) && <section className="recruiter-section"><h3>Education & experience context</h3>{r.education.map(e => <p key={e}>{e}</p>)}{r.experience.map(e => <p key={e}>{e}</p>)}<Link to="/cv">Review CV →</Link></section>}
  <p className="recruiter-limitations">Local, deterministic analysis recognises portfolio technologies and {r.categoryCount} shared engineering categories, plus education, tenure and certification context. Ecosystems help retrieve evidence; related technologies do not prove a specific tool. Unrecognised requirements, mandatory/preferred distinctions, leadership, production scale and nontechnical criteria need manual review. Only the requirements shown contribute to the percentage.</p>
 </div>;
}
